addressbook-web/src/main/java/se/ironic/addressbook/service/ContactServlet.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se.ironic.addressbook.service;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.ejb.EJB;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import se.ironic.addressbook.domain.Address;
import se.ironic.addressbook.domain.Contact;

/**
 *
 * @author Peter
 */
@WebServlet(name = "ContactServlet", urlPatterns = {"/contact"})
public class ContactServlet extends HttpServlet {

    @EJB
    AdressbookService adressbookService;

    /**
     * Processes requests for both HTTP
     * <code>GET</code> and
     * <code>POST</code> methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        try {
            /* TODO output your page here. You may use following sample code. */
            
            if(request.getParameter("create")!=null) {
                Contact nContact = new Contact();
                nContact.setFirstname(request.getParameter("fname"));
                nContact.setLastname(request.getParameter("lname"));
                adressbookService.saveContact(nContact);
            }
            
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ContactServlet</title>");
            List<Contact> findAllContacts = adressbookService.findAllContacts();
            if (findAllContacts == null || findAllContacts.isEmpty()) {
                out.println("Inga kontakter");
            }
            
            for (Contact c : findAllContacts) {
                out.println(String.format("%1$s %2$s<br>", c.getFirstname(), c.getLastname()));
                out.println("<ul>");
                for(Address a : c.getAddresses()) {
                    out.print(String.format("<li>%1$s, %2$s %3$s</li>", a.getStreet(), a.getZip(), a.getCity()));
                }
                out.println("</ul>");
            }
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ContactServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        } finally {
            out.close();
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP
     * <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP
     * <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>
}

addressbook-web/src/main/java/se/ironic/addressbook/view/AddressbookBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se.ironic.addressbook.view;

import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import se.ironic.addressbook.service.AdressbookService;
import se.ironic.addressbook.domain.Contact;

/**
 *
 * @author Peter
 */
@Named(value = "addressbookBean")
@SessionScoped
public class AddressbookBean implements Serializable {

    @EJB
    AdressbookService addressbookService;
    private List<Contact> contacts;

    /**
     * Creates a new instance of AddressbookBean
     */
    public AddressbookBean() {
    }

    @PostConstruct
    private void init() {
        contacts = addressbookService.findAllContacts();
    }

    public String refresh() {
        contacts = addressbookService.findAllContacts();
        return "addressbook.xhtml";
    }

    public void setContacts(List<Contact> contacts) {
        this.contacts = contacts;
    }

    public List<Contact> getContacts() {
        return contacts;
    }

    @SuppressWarnings("unchecked")
    public static <T> T findBean(String beanName) {
        FacesContext context = FacesContext.getCurrentInstance();
        return (T) context.getApplication().evaluateExpressionGet(context, "#{" + beanName + "}", Object.class);
    }

    public String loadContact() {
        FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("id");
        ContactBean contactBean = (ContactBean) findBean("contactBean");
        
        Long id = 31L;
        Contact c = addressbookService.findContactById(id);
        contactBean.setContact(c);
        return "contact.xhtml";
    }
}

addressbook-web/src/main/java/se/ironic/addressbook/view/ContactBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se.ironic.addressbook.view;

import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import se.ironic.addressbook.domain.Contact;
import se.ironic.addressbook.domain.Phone;

/**
 *
 * @author Peter
 */
@Named(value = "contactBean")
@RequestScoped
public class ContactBean {

    private Contact contact = new Contact();

    public Contact getContact() {
        return contact;
    }

    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public List<Phone> getPhones() {
        List<Phone> pList = new ArrayList<Phone>();
        pList.addAll(getContact().getPhones());
        return pList;
    }
}

addressbook-web/src/main/java/se/ironic/addressbook/view/TreeBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.ironic.addressbook.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.swing.tree.TreeNode;
import org.richfaces.component.UITree;
import org.richfaces.event.TreeSelectionChangeEvent;
//import org.richfaces.model.TreeNode;

/**
 *
 * @author Peter
 */
// TODO kan inject.ManagedBean användas?
@ManagedBean(name = "treeBean")
@ViewScoped
public class TreeBean implements Serializable {

    private List<TreeNode> rootNodes = new ArrayList<TreeNode>();
    TreeNode currentSelection;

    @PostConstruct
    public void init() {
        GenTreeNode<Org> root = new GenTreeNode<Org>();
        Org buildOrgTree = buildOrgTree();
        orgToTreeNodes(buildOrgTree, root);
        rootNodes.add(root);
    }

    public List<TreeNode> getRootNodes() {
        return rootNodes;
    }

    public void setRootNodes(List<TreeNode> rootNodes) {
        this.rootNodes = rootNodes;
    }

    public void selectionChanged(TreeSelectionChangeEvent selectionChangeEvent) {
        System.out.println("selectionChangeEvent");
        List<Object> selection = new ArrayList<Object>(selectionChangeEvent.getNewSelection());
        Object currentSelectionKey = selection.get(0);
        UITree tree = (UITree) selectionChangeEvent.getSource();

        Object storedKey = tree.getRowKey();
        tree.setRowKey(currentSelectionKey);
        currentSelection = (TreeNode) tree.getRowData();
        tree.setRowKey(storedKey);
    }

    private void orgToTreeNodes(Org org, GenTreeNode<Org> node) {
        node.setData(org);
        if (!org.getChildren().isEmpty()) {
            for (Org oc : org.getChildren()) {
                GenTreeNode<Org> newTreeNode = new GenTreeNode<Org>();
                node.addChild(newTreeNode);
                newTreeNode.setParent(node);
                orgToTreeNodes(oc, newTreeNode);
            }
        }
    }

    public Org buildOrgTree() {
        Org org = new Org(1, "Company head");
        org.getChildren().add(new Org(2, "HQ"));
        org.getChildren().add(new Org(3, "Sales"));
        Org it = new Org(4, "IT");
        org.getChildren().add(it);
        it.getChildren().add(new Org(4, "R&D"));
        return org;
    }

    public TreeNode getCurrentSelection() {
        return currentSelection;
    }

    public void setCurrentSelection(TreeNode currentSelection) {
        this.currentSelection = currentSelection;
    }

}

addressbook-web/src/main/java/se/ironic/addressbook/view/WaitBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package se.ironic.addressbook.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 *
 * @author Peter
 */
@Named
@RequestScoped
public class WaitBean {
    public void doIt() {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(WaitBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

addressbook-web/src/main/webapp/addressbook.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">

    <body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="title">Addressbook JSF</ui:define>

            <ui:define name="body">
                <rich:panel header="Addressbook">
                    <h:form>

                        <rich:dataTable var="contact" value="#{addressbookBean.contacts}">
                            <f:facet name="header">Contacts</f:facet>
                            <rich:column>
                                <f:facet name="header">Id</f:facet>
                                <h:outputText value="#{contact.id}"/>
                            </rich:column>
                            <rich:column>
                                <f:facet name="header">Firstname</f:facet>
                                <h:outputText value="#{contact.firstname}"/>
                            </rich:column>
                            <rich:column>
                                <f:facet name="header">Lastname</f:facet>
                                <h:outputText value="#{contact.lastname}"/>
                            </rich:column>
                            <rich:column>
                                <f:facet name="header"></f:facet>
                                <h:commandLink value="Edit" action="#{addressbookBean.loadContact()}">
                                    <f:param name="id" value="#{contact.id}"/>
                                </h:commandLink>
                            </rich:column>
                        </rich:dataTable>
                    </h:form>
                </rich:panel>
            </ui:define>
        </ui:composition>
    </body>
</html>

addressbook-web/src/main/webapp/contact.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">

    <body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="title">Contact</ui:define>

            <ui:define name="body">
                <rich:panel header="Contact">
                    <h:form>
                        <h:outputText value="#{contactBean.contact.id}"/><br/>
                        <h:outputText value="#{contactBean.contact.firstname}"/><br/>
                        <h:outputText value="#{contactBean.contact.lastname}"/><br/>
                    </h:form>
                </rich:panel>
                <rich:panel>
                    <rich:dataTable var="p" value="#{contactBean.phones}">
                        <f:facet name="header">Phones</f:facet>
                        <rich:column>
                            <f:facet name="header">Country code</f:facet>
                            <h:outputText value="#{p.countryCode}"/>
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">Area code</f:facet>
                            <h:outputText value="#{p.areaCode}"/>
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">Number</f:facet>
                            <h:outputText value="#{p.number}"/>
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">Type</f:facet>
                            <h:outputText value="#{p.type}"/>
                        </rich:column>
                    </rich:dataTable>
                </rich:panel>
            </ui:define>
        </ui:composition>
    </body>
</html>

addressbook-web/src/main/webapp/tree.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">

    <body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="title">Contact</ui:define>
            
            <ui:define name="body">
                <h:form>
                    user: #{authBean.loggedInUser} is loggedin [<h:outputText value="#{authBean.loggedIn()}"/>]
                    <h:commandLink value="Logout" action="#{authBean.logout()}"/>
                </h:form>
                <h:panelGroup>
                    <h:form>
                        <rich:panel header="Tree">
                            <rich:tree id="tree" var="node" value="#{treeBean.rootNodes}" toggleType="client"
                                       selectionType="ajax" selectionChangeListener="#{treeBean.selectionChanged}">
                                <rich:treeNode>#{node.data.name}</rich:treeNode>
                            </rich:tree>
                        </rich:panel>
                        
                    </h:form>
                    <a4j:outputPanel ajaxRendered="true" layout="block">
                        <rich:panel  header="Current Selection" rendered="#{not empty treeBean.currentSelection}">
                            <h:outputText value="Id: " />
                            <h:outputText value="#{treeBean.currentSelection.data.id}" />
                            <br/>
                            <h:outputText value="Name: " />
                            <h:outputText value="#{treeBean.currentSelection.data.name}" />
                        </rich:panel>
                    </a4j:outputPanel>
                </h:panelGroup>
            </ui:define>
        </ui:composition>
    </body>
</html>

addressbook-web/src/main/webapp/tree2.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">

    <body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="title">Contact</ui:define>

            <ui:define name="body">
                <h:panelGroup>
                    <h:form>
                        <rich:panel header="Tree">
                            <rich:tree toggleType="ajax" 
                                       var="org"
                                       selectionType="ajax"
                                       selectionChangeListener="#{treeBean2.selectionChanged}">
                                <rich:treeModelRecursiveAdaptor roots="#{treeBean2.rootNodes}" nodes="#{org.children}">
                                    <rich:treeNode>
                                        #{org.name}
                                    </rich:treeNode>
                                </rich:treeModelRecursiveAdaptor>
                            </rich:tree>
                        </rich:panel>
                    </h:form>
                    <a4j:outputPanel ajaxRendered="true" layout="block">
                        <rich:panel  header="Current Selection" rendered="#{not empty treeBean2.currentSelection}">
                            <h:outputText value="Id: " />
                            <h:outputText value="#{treeBean2.currentSelection.id}" />
                            <br/>
                            <h:outputText value="Name: " />
                            <h:outputText value="#{treeBean2.currentSelection.name}" />
                        </rich:panel>
                    </a4j:outputPanel>
                </h:panelGroup>
            </ui:define>
        </ui:composition>
    </body>
</html>

addressbook-web/src/main/webapp/tree3.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">

    <body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="title">Contact</ui:define>

            <ui:define name="body">
                <h:panelGroup>
                    <h:form>
                        <rich:panel header="Tree">
                            <rich:tree switchType="client"
                                       var="item"
                                       selectionChangeListener="#{treeBean3.selectionChanged}">
                                <rich:treeModelAdaptor nodes="#{treeBean3.rootNodes}">
                                    <rich:treeNode>
                                        #{item.name}
                                    </rich:treeNode>
                                    <rich:treeModelAdaptor nodes="#{item.children}">
                                        <rich:treeNode>
                                            #{item.name}
                                        </rich:treeNode>
                                        <rich:treeModelAdaptor nodes="#{item.staff}">
                                            <rich:treeNode>
                                                #{item.name}
                                            </rich:treeNode>
                                            <rich:treeModelAdaptor nodes="#{item.skills}">
                                            <rich:treeNode>
                                                #{item.name}
                                            </rich:treeNode>
                                        </rich:treeModelAdaptor>
                                        </rich:treeModelAdaptor>
                                    </rich:treeModelAdaptor>
                                </rich:treeModelAdaptor>
                            </rich:tree>
                        </rich:panel>
                    </h:form>
                    <a4j:outputPanel ajaxRendered="true" layout="block">
                        <rich:panel  header="Current Org" rendered="#{not empty treeBean3.currentOrg}">
                            <h:outputText value="Id: " />
                            <h:outputText value="#{treeBean3.currentOrg.id}" />
                            <br/>
                            <h:outputText value="Name: " />
                            <h:outputText value="#{treeBean3.currentOrg.name}" />
                        </rich:panel>
                        <rich:panel  header="Current Staff" rendered="#{not empty treeBean3.currentStaff}">
                            <h:outputText value="Name: " />
                            <h:outputText value="#{treeBean3.currentStaff.name}" />
                            <br/>
                            <h:outputText value="Function: " />
                            <h:outputText value="#{treeBean3.currentStaff.function}" />
                        </rich:panel>
                    </a4j:outputPanel>
                </h:panelGroup>
            </ui:define>
        </ui:composition>
    </body>
</html>

addressbook-web/src/main/webapp/tree4.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">

    <body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="title">Contact</ui:define>

            <ui:define name="body">
                <h:panelGroup>
                    <h:form>
                        <rich:panel header="Tree">
                            <rich:tree id="tree" var="node" value="#{treeBean4.root}" toggleType="client"
                                       selectionType="ajax" selectionChangeListener="#{treeBean4.selectionChanged}">
                                <rich:treeSelectionChangeListener listener="#{treeBean4}"/>
                                <rich:treeNode>#{node.data.name}</rich:treeNode>
                            </rich:tree>
                        </rich:panel>
                    </h:form>
                    <a4j:outputPanel ajaxRendered="true" layout="block">
                        <rich:panel  header="Current Selection" rendered="#{not empty treeBean4.currentSelection}">
                            <h:outputText value="Id: " />
                            <h:outputText value="#{treeBean4.currentSelection.data.id}" />
                            <br/>
                            <h:outputText value="Name: " />
                            <h:outputText value="#{treeBean4.currentSelection.data.name}" />
                        </rich:panel>
                    </a4j:outputPanel>
                </h:panelGroup>
            </ui:define>
        </ui:composition>
    </body>
</html>

addressbook-web/src/main/webapp/wait.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <a4j:commandButton value="Do something" 
                               action="#{waitBean.doIt()}"
                               status="ajaxStatus"/>
        </h:form>

        <a4j:status id="ajaxStatus"
                    name="ajaxStatus"
                    onstart="#{rich:component('waitPanel')}.show('',{top:'40px', left:'80px',height:'100px', width:'200px'})"
                    onstop="#{rich:component('waitPanel')}.hide()" />

        <rich:popupPanel id="waitPanel" style="text-align:center" modal="true">
            <h:outputText value="Please wait..."
                          style="font-weight:bold;font-size:large" />
        </rich:popupPanel>
    </h:body>
</html>